spring:
  datasource:
    url: jdbc:mysql://127.0.0.1/springbootjpa?useUnicode=true&characterEncoding=utf8&useSSL=false # 数据库连接地址
    username: root # 用户名
    password: 123456 # 密码
    driverClassName: com.mysql.jdbc.Driver # 数据库驱动
  jpa:
    show-sql: true #打印sql