spring:
  datasource:
    url: jdbc:mysql://120.76.201.118/springbootjpa?useUnicode=true&characterEncoding=utf8&useSSL=false # 数据库连接地址
    username: root # 用户名
    password: 123456.Com # 密码
    driverClassName: com.mysql.jdbc.Driver # 数据库驱动
  jpa:
    show-sql: true